title: Unsupervised Learning
author: Ryan Hastings
email: buoyant.gas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dipping my toes in the stream of data science, so a blog on GitHub seems like a pretty good idea...
# social links
twitter_username: BuoyantGas
github_username:  RyanHastings

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-tactile
